import { useEffect, useState } from 'react';
import { History, Trash2, Download, Search, Clock, Activity } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import type { ScanHistory } from '../lib/supabase';

const TOOL_NAMES: Record<string, string> = {
  dns_lookup: 'DNS Lookup',
  http_headers: 'HTTP Header Analyzer',
  ssl_check: 'SSL Checker',
  whois_lookup: 'WHOIS Lookup',
  port_scan: 'Port Scanner',
  cve_search: 'CVE Search',
  url_reputation: 'URL Reputation Check',
};

export default function ScanHistoryPage() {
  const { profile } = useAuth();
  const [history, setHistory] = useState<ScanHistory[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [toolFilter, setToolFilter] = useState('all');
  const [selectedScan, setSelectedScan] = useState<ScanHistory | null>(null);

  useEffect(() => {
    if (!profile) return;
    const fetchHistory = async () => {
      const { data } = await supabase
        .from('scan_history')
        .select('*')
        .eq('user_id', profile.id)
        .order('created_at', { ascending: false });
      setHistory(data as ScanHistory[] ?? []);
      setLoading(false);
    };
    fetchHistory();
  }, [profile]);

  const handleDelete = async (id: string) => {
    await supabase.from('scan_history').delete().eq('id', id);
    setHistory(prev => prev.filter(h => h.id !== id));
    if (selectedScan?.id === id) setSelectedScan(null);
  };

  const handleDownload = (scan: ScanHistory) => {
    const report = generateReport(scan);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scan-report-${scan.tool_type}-${scan.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateReport = (scan: ScanHistory): string => {
    const date = new Date(scan.created_at).toLocaleString();
    return `
========================================
  CYBERLEARN SECURITY SCAN REPORT
========================================

Scan ID:     ${scan.id}
Tool:        ${TOOL_NAMES[scan.tool_type] ?? scan.tool_type}
Target:      ${scan.target}
Status:      ${scan.status}
Date:        ${date}

----------------------------------------
  SCAN RESULTS
----------------------------------------

${JSON.stringify(scan.result, null, 2)}

----------------------------------------
  REPORT GENERATED BY CYBERLEARN
  https://cyberlearn.example.com
========================================
`.trim();
  };

  const filtered = history.filter(h => {
    if (search && !h.target.toLowerCase().includes(search.toLowerCase())) return false;
    if (toolFilter !== 'all' && h.tool_type !== toolFilter) return false;
    return true;
  });

  const toolTypes = ['all', ...Object.keys(TOOL_NAMES)];

  if (loading) {
    return <div className="container-app py-20"><div className="card h-96 animate-pulse bg-neutral-200 dark:bg-neutral-800" /></div>;
  }

  return (
    <div className="container-app py-8 animate-fade-in">
      <div className="mb-8">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-100 text-primary-600 dark:bg-primary-900/30 dark:text-primary-400">
            <History className="h-5 w-5" />
          </div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Scan History</h1>
            <p className="text-sm text-neutral-500">View and download your previous security scan results.</p>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
          <input
            type="text"
            placeholder="Search by target..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="input pl-10"
          />
        </div>
        <select value={toolFilter} onChange={(e) => setToolFilter(e.target.value)} className="input sm:w-48">
          {toolTypes.map(t => (
            <option key={t} value={t}>{t === 'all' ? 'All Tools' : TOOL_NAMES[t] ?? t}</option>
          ))}
        </select>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* History list */}
        <div className="lg:col-span-1">
          <div className="card overflow-hidden">
            <div className="border-b border-neutral-200 p-3 dark:border-neutral-800">
              <p className="text-xs font-semibold uppercase tracking-wider text-neutral-500">
                {filtered.length} scan{filtered.length !== 1 ? 's' : ''}
              </p>
            </div>
            <div className="max-h-[500px] overflow-y-auto scrollbar-thin">
              {filtered.length === 0 ? (
                <p className="p-8 text-center text-sm text-neutral-500">No scans found.</p>
              ) : (
                filtered.map(scan => (
                  <div
                    key={scan.id}
                    className={`group border-b border-neutral-100 p-3 cursor-pointer transition-colors dark:border-neutral-800 ${
                      selectedScan?.id === scan.id ? 'bg-primary-50 dark:bg-primary-900/20' : 'hover:bg-neutral-50 dark:hover:bg-neutral-800/50'
                    }`}
                    onClick={() => setSelectedScan(scan)}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{scan.target}</p>
                        <p className="text-xs text-neutral-500">{TOOL_NAMES[scan.tool_type] ?? scan.tool_type}</p>
                        <p className="text-xs text-neutral-400 flex items-center gap-1 mt-1">
                          <Clock className="h-3 w-3" />
                          {new Date(scan.created_at).toLocaleString()}
                        </p>
                      </div>
                      <div className="flex gap-1 opacity-0 group-hover:opacity-100">
                        <button onClick={(e) => { e.stopPropagation(); handleDownload(scan); }} className="text-neutral-400 hover:text-primary-600">
                          <Download className="h-3.5 w-3.5" />
                        </button>
                        <button onClick={(e) => { e.stopPropagation(); handleDelete(scan.id); }} className="text-neutral-400 hover:text-error-500">
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Detail view */}
        <div className="lg:col-span-2">
          {selectedScan ? (
            <div className="card p-6 animate-fade-in">
              <div className="mb-4 flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold">{TOOL_NAMES[selectedScan.tool_type] ?? selectedScan.tool_type}</h2>
                  <p className="text-sm text-neutral-500">Target: <span className="font-mono">{selectedScan.target}</span></p>
                </div>
                <button onClick={() => handleDownload(selectedScan)} className="btn-secondary">
                  <Download className="h-4 w-4" /> Download Report
                </button>
              </div>
              <div className="rounded-lg bg-neutral-900 p-4 overflow-x-auto">
                <pre className="text-xs text-neutral-300 font-mono whitespace-pre-wrap break-all">
                  {JSON.stringify(selectedScan.result, null, 2)}
                </pre>
              </div>
            </div>
          ) : (
            <div className="card p-12 text-center">
              <Activity className="mx-auto h-12 w-12 text-neutral-400" />
              <p className="mt-4 text-lg font-medium">Select a scan to view details</p>
              <p className="mt-1 text-sm text-neutral-500">Click on any scan from the list to see full results.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
